# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

steps:
  
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: Docker@2
  displayName: login
  inputs:
    command: login
    containerRegistry: Docker Hub

- task: Docker@2
  inputs:
    command: build
    containerRegistry: Docker Hub
    repository: $(Build.SourcesDirectory)/hawxy13/fortifydocker/fortify-ci-tools
    tags: latest
    


- task: FortifySCA@7
  inputs:
    runBuildTranslate: true
    applicationType: 'other'
    buildToolOptions: 'mvn com.fortify.sca.plugins.maven:sca-maven-plugin:translate'
    fortifyBuildId: 'MananDoshi04.8Ball'
    runFortifyClean: true
    runFortifyRulepackUpdate: false
    fortifyScanType: 'LocalScan'
    runFortifyUpload: true
    fortifyServerName: 'SSC'
    fortifyApplicationName: 'EightBall'
    fortifyApplicationVersion: '1'

#- task: FortifySCA@6
#  inputs:
#    runBuildTranslate: true
#    applicationType: 'other'
#    buildToolOptions: 'mvn com.fortify.sca.plugins.maven:sca-maven-plugin:translate'
#    fortifyBuildId: '8ball'
#    runFortifyRulepackUpdate: false
#    runFortifyClean: true
#    scaVerbose: false
#    scaDebug: false
#    runFortifyScan: true
#    fortifyScanType: 'LocalScan'
#    runFortifyUpload: true
#    fortifyServerName: 'SSC'
#    fortifyApplicationName: 'EightBall'
#    fortifyApplicationVersion: '1'
