# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

steps:
  
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: InstallFortifySCA@7
  inputs:
    InstallerPath: 'C:\Program Files\Fortify\Fortify_SCA_and_Apps_21.2.3\Fortify_SCA_and_Apps_21.2.3_windows_x64.exe.'
    VS2015: false
    LicenseFile: 'C:\Users\Administrator\Downloads\Fortify.License'
    RunFortifyRulepackUpdate: false
- task: FortifySCA@7
  inputs:
- task: FortifySCA@7
  inputs:
    applicationType: 'dotnet'
    fortifyProjects: '**\*.sln'
    fortifyScanType: 'LocalScan'
    runFortifyUpload: true
    fortifyServerName: 'SSC'
    fortifyApplicationName: '8Ball'
    applicationType: 'other'
    fortifyBuildId: '8ball'
    runFortifyRulepackUpdate: false
    fortifyScanType: 'LocalScan'

#- task: FortifySCA@6
#  inputs:
#    runBuildTranslate: true
#    applicationType: 'other'
#    buildToolOptions: 'mvn com.fortify.sca.plugins.maven:sca-maven-plugin:translate'
#    fortifyBuildId: '8ball'
#    runFortifyRulepackUpdate: false
#    runFortifyClean: true
#    scaVerbose: false
#    scaDebug: false
#    runFortifyScan: true
#    fortifyScanType: 'LocalScan'
#    runFortifyUpload: true
#    fortifyServerName: 'SSC'
#    fortifyApplicationName: 'EightBall'
#    fortifyApplicationVersion: '1'
