version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - compile-build
      - fod-sast:
          requires:
            - compile-build

jobs:
  compile-build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - hello-spring-mvn-V2-{{ checksum "pom.xml" }}
            - hello-spring-mvn-V2
      - run: mvn dependency:go-offline
      - run:
          name: Build 
          command: |
            mvn clean compile
      - save_cache:
          paths:
           - ~/.m2
          key: hello-spring-mvn-V2-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports

  fod-sast:
    docker:
      - image: fortifydocker/fortify-ci-tools:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - hello-spring-mvn-V2-{{ checksum "pom.xml" }}
            - hello-spring-mvn-V2
      - run: mvn dependency:go-offline
      - run:
          name: FoD SAST Using fortify-ci-tools 
          command: |
            $PACKAGE_OPTS: "-bt mvn" 
            scancentral package $PACKAGE_OPTS -o package.zip 
            java -jar $FOD_UPLOAD -z package.zip -aurl $FOD_API_URL -purl $FOD_URL -rid "$FOD_RELEASE" -tc "$FOD_TENANT" -uc "$FOD_USERNAME" "$FOD_PAT" $FOD_UPLOADER_OPTS -n "$FOD_NOTES"

  