ersion: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - unit-test
      - publish-docker:
          requires:
            - unit-test

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - hello-spring-mvn-V2-{{ checksum "pom.xml" }}
            - hello-spring-mvn-V2
      - run: mvn dependency:go-offline
      - run:
          name: Build 
          command: |
            mvn clean compile
      - save_cache:
          paths:
           - ~/.m2
          key: hello-spring-mvn-V2-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports

  fod-sast:
    docker:
      - image: fortifydocker/fortify-ci-tools:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - hello-spring-mvn-V2-{{ checksum "pom.xml" }}
            - hello-spring-mvn-V2
      - run: mvn dependency:go-offline
      - run:
          name: Build 
          command: |
            mvn clean compile
      - save_cache:
          paths:
           - ~/.m2
          key: hello-spring-mvn-V2-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports

  